/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminInfo { 'principal' : Principal, 'name' : string }
export interface UserProfile { 'name' : string }
export interface UserProfileInfo {
  'principal' : Principal,
  'name' : string,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAdmins' : ActorMethod<[], Array<AdminInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileInfo]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoogleSheetsDownloadLink' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], UserProfileInfo>,
  'getUserRole' : ActorMethod<[], [] | [UserRole]>,
  'hasProfile' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];