/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminInfo { 'principal' : Principal, 'name' : string }
export interface BackupEntry {
  'id' : bigint,
  'sensorLabelsJson' : string,
  'sensorGroupsJson' : string,
  'backupLabel' : string,
  'advancedConfigJson' : string,
  'sensorDataJson' : string,
  'timestampMs' : bigint,
  'loggerId' : bigint,
}
export interface BackupMeta {
  'id' : bigint,
  'backupLabel' : string,
  'timestampMs' : bigint,
  'loggerId' : bigint,
}
export interface UserProfile { 'name' : string }
export interface UserProfileInfo {
  'principal' : Principal,
  'name' : string,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBackup' : ActorMethod<[bigint], undefined>,
  'getAdvancedChartConfigForId' : ActorMethod<[bigint], string>,
  'getAllAdmins' : ActorMethod<[], Array<AdminInfo>>,
  'getAllBackupsMeta' : ActorMethod<[], Array<BackupMeta>>,
  'getAllLoggerLabels' : ActorMethod<[], Array<[bigint, string]>>,
  'getAllSensorLabelsForId' : ActorMethod<[bigint], Array<[bigint, string]>>,
  'getBackupById' : ActorMethod<[bigint], [] | [BackupEntry]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileInfo]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoogleSheetsDownloadLink' : ActorMethod<[], string>,
  'getGrantedAdmins' : ActorMethod<[], Array<Principal>>,
  'getSensorGroupsForId' : ActorMethod<[bigint], string>,
  'getUserProfile' : ActorMethod<[Principal], UserProfileInfo>,
  'getUserRole' : ActorMethod<[], [] | [UserRole]>,
  'grantAdminRole' : ActorMethod<[Principal], boolean>,
  'hasProfile' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isConceptMachineVisible' : ActorMethod<[], boolean>,
  'resetSensorLabelsForId' : ActorMethod<[bigint], undefined>,
  'saveAdvancedChartConfigForId' : ActorMethod<[bigint, string], undefined>,
  'saveBackup' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSensorGroupsForId' : ActorMethod<[bigint, string], undefined>,
  'setConceptMachineVisible' : ActorMethod<[boolean], undefined>,
  'setLoggerIdLabel' : ActorMethod<[bigint, string], undefined>,
  'setSensorLabel' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];