/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const BackupMeta = IDL.Record({
  'id' : IDL.Nat,
  'backupLabel' : IDL.Text,
  'timestampMs' : IDL.Int,
  'loggerId' : IDL.Nat,
});
export const BackupEntry = IDL.Record({
  'id' : IDL.Nat,
  'sensorLabelsJson' : IDL.Text,
  'sensorGroupsJson' : IDL.Text,
  'backupLabel' : IDL.Text,
  'advancedConfigJson' : IDL.Text,
  'sensorDataJson' : IDL.Text,
  'timestampMs' : IDL.Int,
  'loggerId' : IDL.Nat,
});
export const UserProfileInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'isAdmin' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBackup' : IDL.Func([IDL.Nat], [], []),
  'getAdvancedChartConfigForId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getAllAdmins' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
  'getAllBackupsMeta' : IDL.Func([], [IDL.Vec(BackupMeta)], ['query']),
  'getAllLoggerLabels' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllSensorLabelsForId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getBackupById' : IDL.Func([IDL.Nat], [IDL.Opt(BackupEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileInfo)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoogleSheetsDownloadLink' : IDL.Func([], [IDL.Text], ['query']),
  'getGrantedAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getSensorGroupsForId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfileInfo], ['query']),
  'getUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'grantAdminRole' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isConceptMachineVisible' : IDL.Func([], [IDL.Bool], ['query']),
  'resetSensorLabelsForId' : IDL.Func([IDL.Nat], [], []),
  'saveAdvancedChartConfigForId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveBackup' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSensorGroupsForId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setConceptMachineVisible' : IDL.Func([IDL.Bool], [], []),
  'setLoggerIdLabel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setSensorLabel' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const BackupMeta = IDL.Record({
    'id' : IDL.Nat,
    'backupLabel' : IDL.Text,
    'timestampMs' : IDL.Int,
    'loggerId' : IDL.Nat,
  });
  const BackupEntry = IDL.Record({
    'id' : IDL.Nat,
    'sensorLabelsJson' : IDL.Text,
    'sensorGroupsJson' : IDL.Text,
    'backupLabel' : IDL.Text,
    'advancedConfigJson' : IDL.Text,
    'sensorDataJson' : IDL.Text,
    'timestampMs' : IDL.Int,
    'loggerId' : IDL.Nat,
  });
  const UserProfileInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBackup' : IDL.Func([IDL.Nat], [], []),
    'getAdvancedChartConfigForId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getAllAdmins' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
    'getAllBackupsMeta' : IDL.Func([], [IDL.Vec(BackupMeta)], ['query']),
    'getAllLoggerLabels' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllSensorLabelsForId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getBackupById' : IDL.Func([IDL.Nat], [IDL.Opt(BackupEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileInfo)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoogleSheetsDownloadLink' : IDL.Func([], [IDL.Text], ['query']),
    'getGrantedAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getSensorGroupsForId' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfileInfo], ['query']),
    'getUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'grantAdminRole' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isConceptMachineVisible' : IDL.Func([], [IDL.Bool], ['query']),
    'resetSensorLabelsForId' : IDL.Func([IDL.Nat], [], []),
    'saveAdvancedChartConfigForId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveBackup' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSensorGroupsForId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setConceptMachineVisible' : IDL.Func([IDL.Bool], [], []),
    'setLoggerIdLabel' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setSensorLabel' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };